# Generated by Django 2.1.5 on 2020-05-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailgetter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='reciever',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='sender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
