# Generated by Django 2.1.5 on 2020-05-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailgetter', '0002_auto_20200508_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
